# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

thetaDraw <- function(tree, W, X, y, m, sigma, theta, Lambda) {
    .Call(`_rdBART_thetaDraw`, tree, W, X, y, m, sigma, theta, Lambda)
}

yDraw <- function(tree, W, X, yFit, draws) {
    .Call(`_rdBART_yDraw`, tree, W, X, yFit, draws)
}

yPred <- function(tree, W, X, yFit, yDraws) {
    .Call(`_rdBART_yPred`, tree, W, X, yFit, yDraws)
}

partialResid <- function(y, yPredMat, remove) {
    .Call(`_rdBART_partialResid`, y, yPredMat, remove)
}

treeRSS <- function(yPred, y) {
    .Call(`_rdBART_treeRSS`, yPred, y)
}

treeListRSS <- function(yPredMat, y) {
    .Call(`_rdBART_treeListRSS`, yPredMat, y)
}

sigPost <- function(nu, lambda, m, nobs, yPredMat, y) {
    .Call(`_rdBART_sigPost`, nu, lambda, m, nobs, yPredMat, y)
}

lambdaPosteriorOne <- function(Xnode, m, sigma) {
    .Call(`_rdBART_lambdaPosteriorOne`, Xnode, m, sigma)
}

lambdaPosterior <- function(tree, W, X, m, sigma) {
    .Call(`_rdBART_lambdaPosterior`, tree, W, X, m, sigma)
}

thetaPosteriorOne <- function(X, y, Lambda, sigma) {
    .Call(`_rdBART_thetaPosteriorOne`, X, y, Lambda, sigma)
}

thetaPosterior <- function(tree, W, X, y, Lambda, sigma) {
    .Call(`_rdBART_thetaPosterior`, tree, W, X, y, Lambda, sigma)
}

logLikTree <- function(tree, W, X, y, m, sigma, theta, Lambda) {
    .Call(`_rdBART_logLikTree`, tree, W, X, y, m, sigma, theta, Lambda)
}

mhRatio <- function(tree, treeNew, W, X, y, m, sigma, alpha, beta, ll0) {
    .Call(`_rdBART_mhRatio`, tree, treeNew, W, X, y, m, sigma, alpha, beta, ll0)
}

newTree <- function(tree, treeNew, W, X, y, m, sigma, alpha, beta, ll0) {
    .Call(`_rdBART_newTree`, tree, treeNew, W, X, y, m, sigma, alpha, beta, ll0)
}

rdBART <- function(W, X, y, alpha, beta, nu, lambda, m, nDraws, burn) {
    .Call(`_rdBART_rdBART`, W, X, y, alpha, beta, nu, lambda, m, nDraws, burn)
}

node <- function(nodeID, splitVar, splitVal) {
    .Call(`_rdBART_node`, nodeID, splitVar, splitVal)
}

splits <- function(W) {
    .Call(`_rdBART_splits`, W)
}

avalSplits <- function(tree, splits) {
    .Call(`_rdBART_avalSplits`, tree, splits)
}

bottomNodes <- function(tree) {
    .Call(`_rdBART_bottomNodes`, tree)
}

nBottomNodes <- function(tree) {
    .Call(`_rdBART_nBottomNodes`, tree)
}

nogNodes <- function(tree) {
    .Call(`_rdBART_nogNodes`, tree)
}

nNogNodes <- function(tree) {
    .Call(`_rdBART_nNogNodes`, tree)
}

internalNodes <- function(tree) {
    .Call(`_rdBART_internalNodes`, tree)
}

nInternalNodes <- function(tree) {
    .Call(`_rdBART_nInternalNodes`, tree)
}

pcNodes <- function(tree) {
    .Call(`_rdBART_pcNodes`, tree)
}

nPCNodes <- function(tree) {
    .Call(`_rdBART_nPCNodes`, tree)
}

nodeDepth <- function(nodeID) {
    .Call(`_rdBART_nodeDepth`, nodeID)
}

pSplit <- function(nodeID, alpha, beta) {
    .Call(`_rdBART_pSplit`, nodeID, alpha, beta)
}

pAllSplits <- function(tree, alpha, beta) {
    .Call(`_rdBART_pAllSplits`, tree, alpha, beta)
}

pRules <- function(tree, splits) {
    .Call(`_rdBART_pRules`, tree, splits)
}

pTree <- function(tree, splits, alpha, beta) {
    .Call(`_rdBART_pTree`, tree, splits, alpha, beta)
}

grow <- function(tree, splits) {
    .Call(`_rdBART_grow`, tree, splits)
}

prune <- function(tree) {
    .Call(`_rdBART_prune`, tree)
}

change <- function(tree, splits) {
    .Call(`_rdBART_change`, tree, splits)
}

swap <- function(tree) {
    .Call(`_rdBART_swap`, tree)
}

fit <- function(tree, W) {
    .Call(`_rdBART_fit`, tree, W)
}

proposal <- function(tree, W) {
    .Call(`_rdBART_proposal`, tree, W)
}

whichCpp <- function(vec, value) {
    .Call(`_rdBART_whichCpp`, vec, value)
}

whichList <- function(vec, values) {
    .Call(`_rdBART_whichList`, vec, values)
}

splitMatrix <- function(M, vec, values) {
    .Call(`_rdBART_splitMatrix`, M, vec, values)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_rdBART_mvrnormArma`, n, mu, sigma)
}

