# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

thetaDraw <- function(tree, W, X, y, m, sigma) {
    .Call(`_rdBART_thetaDraw`, tree, W, X, y, m, sigma)
}

yDraw <- function(tree, W, X, y, m, sigma, draws) {
    .Call(`_rdBART_yDraw`, tree, W, X, y, m, sigma, draws)
}

thetaDrawsList <- function(treeList, W, X, y, m, sigma) {
    .Call(`_rdBART_thetaDrawsList`, treeList, W, X, y, m, sigma)
}

partialResid <- function(treeList, remove, W, X, y, m, sigma, draws) {
    .Call(`_rdBART_partialResid`, treeList, remove, W, X, y, m, sigma, draws)
}

lambdaPosteriorOne <- function(Xnode, m, sigma) {
    .Call(`_rdBART_lambdaPosteriorOne`, Xnode, m, sigma)
}

lambdaPosterior <- function(tree, W, X, m, sigma) {
    .Call(`_rdBART_lambdaPosterior`, tree, W, X, m, sigma)
}

thetaPosteriorOne <- function(X, y, Lambda, sigma) {
    .Call(`_rdBART_thetaPosteriorOne`, X, y, Lambda, sigma)
}

thetaPosterior <- function(tree, W, X, y, Lambda, sigma) {
    .Call(`_rdBART_thetaPosterior`, tree, W, X, y, Lambda, sigma)
}

logLikTree <- function(tree, W, X, y, m, sigma, theta, Lambda) {
    .Call(`_rdBART_logLikTree`, tree, W, X, y, m, sigma, theta, Lambda)
}

mhRatio <- function(tree, treeNew, W, X, y, m, sigma, alpha, beta) {
    .Call(`_rdBART_mhRatio`, tree, treeNew, W, X, y, m, sigma, alpha, beta)
}

newTree <- function(tree, treeNew, W, X, y, m, sigma, alpha, beta) {
    .Call(`_rdBART_newTree`, tree, treeNew, W, X, y, m, sigma, alpha, beta)
}

rdBART <- function(W, X, y, alpha, beta, m, nDraws, burn) {
    .Call(`_rdBART_rdBART`, W, X, y, alpha, beta, m, nDraws, burn)
}

node <- function(nodeID, splitVar, splitVal) {
    .Call(`_rdBART_node`, nodeID, splitVar, splitVal)
}

splits <- function(W) {
    .Call(`_rdBART_splits`, W)
}

grow <- function(tree, splits) {
    .Call(`_rdBART_grow`, tree, splits)
}

prune <- function(tree) {
    .Call(`_rdBART_prune`, tree)
}

change <- function(tree, splits) {
    .Call(`_rdBART_change`, tree, splits)
}

swap <- function(tree) {
    .Call(`_rdBART_swap`, tree)
}

fit <- function(tree, W) {
    .Call(`_rdBART_fit`, tree, W)
}

proposal <- function(tree, W) {
    .Call(`_rdBART_proposal`, tree, W)
}

whichCpp <- function(vec, value) {
    .Call(`_rdBART_whichCpp`, vec, value)
}

whichList <- function(vec, values) {
    .Call(`_rdBART_whichList`, vec, values)
}

splitMatrix <- function(M, vec, values) {
    .Call(`_rdBART_splitMatrix`, M, vec, values)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_rdBART_mvrnormArma`, n, mu, sigma)
}

